### ISSUE TITLE
Unknown module(s)

### ISSUE THREAD

**Issue by ghost** [digitalpianism/changepassword#1]
I put your code in app/code/ folder  and follow set up 
php bin/magento setup:upgrade
php bin/magento module:enable DigitalPianism_ChangePassword

but result  : unknows mdule

![image](https://cloud.githubusercontent.com/assets/27570520/25069000/5bd9d2da-229e-11e7-89b9-b449a4bc5b03.png)

Any suggestion ?

**Comment by digitalpianism** [comment]
@prasertkv hi. Would you mind giving me the Magento version you're using so I can investigate the issue

**Comment by ghost** [comment]
Thank you for your reply.
Magento 2.1.6  please.
Because I am new with Magento. So, Could you advise step by step please.

**Comment by digitalpianism** [comment]
@prasertkv Ok when you said "I put your code in app/code folder" what did you do exactly ?

Because if you install the module manually you need to create DigitalPianism/ChangePassword folder in app/code first then copy the file from GitHub into the ChangePassword folder before running the command.

**Comment by jissereitsma** [comment]
@prasertkv Any update on this? Because otherwise it is better to close this ticket.

**Comment by digitalpianism** [comment]
@prasertkv as @jissereitsma suggested I'm closing this ticket because of the lack of further information. feel free to open a new one if you still have the issue
